services:
  # Backend API
  - type: web
    name: stackit-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: stackit-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

  # PostgreSQL Database
  - type: pserv
    name: stackit-db
    plan: free
    env: postgresql
    disk:
      name: stackit-db-disk
      mountPath: /var/lib/postgresql/data
